name: streamlit
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pyarrow
  - pip
  - streamlit>=1.20.0
  - fsspec
  - s3fs
  - openai<1.0.0 # v1.0.0 contains breaking changes
  - foundry-dev-tools
  - snowflake-snowpark-python
  - snowflake-connector-python
  # You can add additional pip dependencies by uncommenting below lines
  # see: https://stackoverflow.com/a/35245610/3652805
  - pip:  
    - altair==5.2.0
    - arrow==1.3.0
    - biopython==1.83
    - blinker==1.7.0
    - cachetools==5.3.2
    - click==8.1.7
    - comm==0.2.1
    - contourpy==1.1.1
    - cycler==0.12.1
    - deprecation==2.1.0
    - docopt==0.6.2
    - emmet-core==0.68.0
    - filelock==3.13.1
    - fonttools==4.49.0
    - fqdn==1.5.1
    - fsspec==2023.12.2
    - future==1.0.0
    - gitdb==4.0.11
    - GitPython==3.1.41
    - huggingface-hub==0.20.3
    - iniconfig==2.0.0
    - ipyspeck==0.6.1
    - ipython==8.12.3
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - isoduration==20.11.0
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema-specifications==2023.12.1
    - jupyter-contrib-core==0.4.2
    - jupyter-contrib-nbextensions==0.7.0
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-nbextensions-configurator==0.6.3
    - jupyter_packaging==0.12.3
    - jupyterlab==4.0.11
    - jupyterlab_widgets==3.0.10
    - kiwisolver==1.4.5
    - latexcodec==2.0.1
    - lxml==5.1.0
    - markdown-it-py==3.0.0
    - matplotlib==3.7.5
    - mdurl==0.1.2
    - mkl-service==2.4.0
    - monty==2023.9.25
    - mp-api==0.35.1
    - mpmath==1.3.0
    - msgpack==1.0.7
    - nbconvert==7.14.2
    - networkx==3.1
    - palettable==3.3.3
    - pandas==2.0.3
    - Pillow==10.1.0
    - pipreqs==0.5.0
    - plotly==5.19.0
    - pluggy==1.3.0
    - ply==3.11
    - protobuf==4.25.2
    - py3Dmol==2.0.4
    - pyarrow==15.0.0
    - pybtex==0.24.0
    - pydantic==1.10.14
    - pydeck==0.8.1b0
    - pymatgen==2023.8.10
    - pyparsing==3.1.1
    - PyQt5==5.15.10
    - pytest==7.4.4
    - referencing==0.32.1
    - regex==2023.12.25
    - ruamel.yaml==0.18.6
    - ruamel.yaml.clib==0.2.8
    - scikit-learn==1.1.2
    - scipy==1.10.1
    - smmap==5.0.1
    - spglib==2.3.1
    - stmol==0.0.9
    - streamlit==1.31.0
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.3
    - threadpoolctl==3.2.0
    - tokenizers==0.13.3
    - toml==0.10.2
    - tomlkit==0.12.3
    - toolz==0.12.1
    - tqdm==4.66.1
    - traitlets==5.14.1
    - transformers==4.24.0
    - types-python-dateutil==2.8.19.20240106
    - tzdata==2023.4
    - tzlocal==5.2
    - uncertainties==3.1.7
    - uri-template==1.3.0
    - validators==0.22.0
    - watchdog==3.0.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - widgetsnbextension==3.5.0
    - yarg==0.1.9
    - torch
    - nglview==3.0.8
    - Requests
    - scikit_learn==1.1.2
